### ISSUE TITLE
deform_attn.so dependency problem

### ISSUE THREAD

**Issue by denizubu** [xg416/DATUM#10]
Hi! I am trying to run a dynamic test with ATSyn_dynamic dataset via this command: 

python test_DATUM_dynamic.py --data_path /home/denizubu/Desktop/AT/testvid/ --info_path /home/denizubu/Desktop/AT/testinf/archery_2923.json -result /home/denizubu/Desktop/AT/Results/ -mp /home/denizubu/Desktop/AT/Pretrained/

However, I am facing this error:

Traceback (most recent call last):
  File "/home/denizubu/Desktop/AT/DATUM/code/test_DATUM_dynamic.py", line 249, in <module>
    main()
  File "/home/denizubu/Desktop/AT/DATUM/code/test_DATUM_dynamic.py", line 208, in main
    model = Model(args).cuda()
  File "/home/denizubu/Desktop/AT/DATUM/code/TM_model/model.py", line 11, in __init__
    self.module = import_module('TM_model.{}'.format(model_name))
  File "/home/denizubu/anaconda3/envs/atenv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/denizubu/Desktop/AT/DATUM/code/TM_model/DATUM.py", line 16, in <module>
    from .op.deform_attn import deform_attn, DeformAttnPack
  File "/home/denizubu/Desktop/AT/DATUM/code/TM_model/op/deform_attn.py", line 19, in <module>
    deform_attn_ext = load(
  File "/home/denizubu/anaconda3/envs/atenv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/home/denizubu/anaconda3/envs/atenv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1318, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/denizubu/anaconda3/envs/atenv/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1701, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/denizubu/.cache/torch_extensions/deform_attn/deform_attn.so: cannot open shared object file: No such file or directory

I think this is due to some version mismatch, but I could not find the exact reason. Is there anyone faced the same problem? Any advices?

**Comment by denizubu** [comment]
Also, I tried to run the test script with --val_info as you suggested. However, there is no --val_info argument in the script. Therefore I tried with --info_path argument. Is this the correct thing to do?

**Comment by Ayt777** [comment]
hello! I encountered the same problem. Could you please tell me how you solved it?
