### ISSUE TITLE
about FPS

### ISSUE THREAD

**Issue by PonyPinkPie** [xg416/DATUM#14]
Dear author, when I try to using Datum-s model, there are some mismatchs between Datum-s.pth and our network. So, I adjust the network in two places, one is `reduction=n_features` in `CAB module` , the other is `deformable_groups=n_features` in `GuidedDeformAttnPack module`. Then, it works. 
However, when using 2 frames in `past_frames` and `future_frames` , both `Datum-s` and `Datum-dynamic` model can not achieve their FPS in report with `960x544x3` resolution (544%8=0, without any more steps). 
So, I guess there are some mistakes in my code, or, the FPS in report is using 1 frame in both `past_frames` and `future_frames`?

**Comment by denizubu** [comment]
> Dear author, when I try to using Datum-s model, there are some mismatchs between Datum-s.pth and our network. So, I adjust the network in two places, one is `reduction=n_features` in `CAB module` , the other is `deformable_groups=n_features` in `GuidedDeformAttnPack module`. Then, it works. However, when using 2 frames in `past_frames` and `future_frames` , both `Datum-s` and `Datum-dynamic` model can not achieve their FPS in report with `960x544x3` resolution (544%8=0, without any more steps). So, I guess there are some mistakes in my code, or, the FPS in report is using 1 frame in both `past_frames` and `future_frames`?

Hi! I am also trying to run DATUM-s for inference but could not manage to do that. Can you tell me how did you do that? I inserted DATUM-s.pth into inference_DATUM_dynamic.py but could not find which parameters should I change exactly. Any help would be appreciated.

**Comment by PonyPinkPie** [comment]
> > Dear author, when I try to using Datum-s model, there are some mismatchs between Datum-s.pth and our network. So, I adjust the network in two places, one is `reduction=n_features` in `CAB module` , the other is `deformable_groups=n_features` in `GuidedDeformAttnPack module`. Then, it works. However, when using 2 frames in `past_frames` and `future_frames` , both `Datum-s` and `Datum-dynamic` model can not achieve their FPS in report with `960x544x3` resolution (544%8=0, without any more steps). So, I guess there are some mistakes in my code, or, the FPS in report is using 1 frame in both `past_frames` and `future_frames`?
> 
> Hi! I am also trying to run DATUM-s for inference but could not manage to do that. Can you tell me how did you do that? I inserted DATUM-s.pth into inference_DATUM_dynamic.py but could not find which parameters should I change exactly. Any help would be appreciated.

so, can you show me the errors?

**Comment by denizubu** [comment]
> > > Dear author, when I try to using Datum-s model, there are some mismatchs between Datum-s.pth and our network. So, I adjust the network in two places, one is `reduction=n_features` in `CAB module` , the other is `deformable_groups=n_features` in `GuidedDeformAttnPack module`. Then, it works. However, when using 2 frames in `past_frames` and `future_frames` , both `Datum-s` and `Datum-dynamic` model can not achieve their FPS in report with `960x544x3` resolution (544%8=0, without any more steps). So, I guess there are some mistakes in my code, or, the FPS in report is using 1 frame in both `past_frames` and `future_frames`?
> > 
> > 
> > Hi! I am also trying to run DATUM-s for inference but could not manage to do that. Can you tell me how did you do that? I inserted DATUM-s.pth into inference_DATUM_dynamic.py but could not find which parameters should I change exactly. Any help would be appreciated.
> 
> so, can you show me the errors?

First, I reduced the number of channels to match DATUM-s but got other mismatch errors. After changing some parameters which I cannot recall, I solved the mismatch problems but now I am getting memory allocation error. This is the output:
video /home/deniz/Videos/road.mp4, input frames 308, h 360 x w 640
[0, 8] [0, 10]
Traceback (most recent call last):
  File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/inference_DATUM_dynamic.py", line 171, in <module>
    output,_ = model((input_, input_))
  File "/home/deniz/anaconda3/envs/datum/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/model.py", line 15, in forward
    outputs = self.module.feed(self.model, iter_samples)
  File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/DATUM.py", line 519, in feed
    outputs = model(inputs)
  File "/home/deniz/anaconda3/envs/datum/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/DATUM.py", line 428, in forward
    flow_update = flow_r + flow_warp(flows_backward[:,i-1,...], flow_r)
  File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/archs.py", line 161, in flow_warp
    grid_y, grid_x = torch.meshgrid(torch.arange(0, h).type_as(x), torch.arange(0, w).type_as(x), indexing='ij')
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by PonyPinkPie** [comment]
> > > > Dear author, when I try to using Datum-s model, there are some mismatchs between Datum-s.pth and our network. So, I adjust the network in two places, one is `reduction=n_features` in `CAB module` , the other is `deformable_groups=n_features` in `GuidedDeformAttnPack module`. Then, it works. However, when using 2 frames in `past_frames` and `future_frames` , both `Datum-s` and `Datum-dynamic` model can not achieve their FPS in report with `960x544x3` resolution (544%8=0, without any more steps). So, I guess there are some mistakes in my code, or, the FPS in report is using 1 frame in both `past_frames` and `future_frames`?
> > > 
> > > 
> > > Hi! I am also trying to run DATUM-s for inference but could not manage to do that. Can you tell me how did you do that? I inserted DATUM-s.pth into inference_DATUM_dynamic.py but could not find which parameters should I change exactly. Any help would be appreciated.
> > 
> > 
> > so, can you show me the errors?
> 
> First, I reduced the number of channels to match DATUM-s but got other mismatch errors. After changing some parameters which I cannot recall, I solved the mismatch problems but now I am getting memory allocation error. This is the output: video /home/deniz/Videos/road.mp4, input frames 308, h 360 x w 640 [0, 8] [0, 10] Traceback (most recent call last): File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/inference_DATUM_dynamic.py", line 171, in output,_ = model((input_, input_)) File "/home/deniz/anaconda3/envs/datum/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/model.py", line 15, in forward outputs = self.module.feed(self.model, iter_samples) File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/DATUM.py", line 519, in feed outputs = model(inputs) File "/home/deniz/anaconda3/envs/datum/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/DATUM.py", line 428, in forward flow_update = flow_r + flow_warp(flows_backward[:,i-1,...], flow_r) File "/home/deniz/Desktop/ATProject/AtmosphericTurbulence/DATUM/code/TM_model/archs.py", line 161, in flow_warp grid_y, grid_x = torch.meshgrid(torch.arange(0, h).type_as(x), torch.arange(0, w).type_as(x), indexing='ij') RuntimeError: CUDA error: an illegal memory access was encountered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

it seems that this error is not related to my problem, but i think you can find answer easily on Intelnet, just copy your error info. :)

**Comment by xg416** [comment]
Hi, to test the speed of the network, you can run 
`python TM_model/DATUM.py` after removing the initial `.` in lines 15-16 of the file. You can also try different resolutions as well.

When measuring the speed of the network, please use `torch.cuda.Event()` and `torch.cuda.synchronize()` functions and don't calculate the first (several) runs of the network to avoid memory loading operations.

**Comment by PonyPinkPie** [comment]
> Hi, to test the speed of the network, you can run `python TM_model/DATUM.py` after removing the initial `.` in lines 15-16 of the file. You can also try different resolutions as well.
> 
> When measuring the speed of the network, please use `torch.cuda.Event()` and `torch.cuda.synchronize()` functions and don't calculate the first (several) runs of the network to avoid memory loading operations.

think you :)
